name: student_link
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  smooth_page_indicator: ^1.1.0
  google_maps_flutter: ^2.2.8
  image: ^4.0.17
  flip_card: ^0.7.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0
  geocoding: ^2.1.0
  image_picker: ^1.0.1
  file_picker: ^5.3.3
  intl: ^0.18.1
  web_socket_channel: ^2.4.0
 



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/login/
    - assets/icons/bottom_nav/news.svg
    - assets/icons/bottom_nav/find.svg
    - assets/icons/bottom_nav/maps.svg
    - assets/icons/bottom_nav/profile.svg
    - assets/icons/app_bar/icon_back.svg
    - assets/icons/social/instagram.svg
    - assets/icons/social/facebook.svg
    - assets/maps_style/maps_style.json
    - assets/markers.json
    - assets/icons/map/card_partners/map.svg
    - assets/icons/map/card_partners/download.svg
    - assets/icons/map/card_partners/notify.svg
    - assets/icons/map/card_partners/qrcode.svg
    - assets/icons/map/card_partners/change_arrow.svg
    - assets/icons/profile/chat.svg
    - assets/icons/profile/menu.svg
    - assets/icons/profile/cap.svg
    - assets/icons/profile/notes.svg
    - assets/images/map/marker/marker_partner.png
    - assets/icons/profile/download.svg
    - assets/icons/immagini_provvisorie/
    - assets/icons/immagini_provvisorie/woman_phone.png
    - assets/icons/immagini_provvisorie/on_boarding_2.png
    - assets/icons/immagini_provvisorie/on_boarding_3.png
    - assets/icons/immagini_provvisorie/on_boarding_4.png
    - assets/icons/immagini_provvisorie/on_boarding_5.png
    - assets/icons/immagini_provvisorie/image_profile.png
    - assets/icons/immagini_provvisorie/back_card.png
    - assets/icons/immagini_provvisorie/back_card_strut.png
    - assets/icons/immagini_provvisorie/appunto.png
    - assets/icons/immagini_provvisorie/pdf.png
    - assets/icons/immagini_provvisorie/delete_account.png
    - assets/icons/immagini_provvisorie/log_out.png
    - assets/icons/immagini_provvisorie/news.png
    - assets/icons/profile/note.svg
    - assets/icons/profile/insert_preview.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
